#!/bin/sh
# sshstart - Start SSHD and set a password (if necessary)
# (C) Klaus Knopper Jun 2001
# changed for standard ssh start scripts (for KANOTIX)
# Joerg Schirottke Jan 2004
# (C) 2004-2006 Stefan Lippers-Hollmann <s.l-h@gmx.de>

# override tool behaviour through distro-defaults
FLL_LIVE_USER="knoppix"
[ -r /etc/default/distro ] && source /etc/default/distro

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

TITLE="SSH Server"

RXVT=""
[ -n "$DISPLAY" ] && RXVT="x-terminal-emulator -e"

[ "`id -u`" != "0" ] && exec $RXVT kanotix-su "$0" "$@"

# use keygen if needed
[ -e /etc/ssh/ssh_host_rsa_key ] || ssh-keygen -t rsa -f /etc/ssh/ssh_host_rsa_key -C '' -N ''
[ -e /etc/ssh/ssh_host_dsa_key ] || ssh-keygen -t dsa -f /etc/ssh/ssh_host_dsa_key -C '' -N ''

[ -x /etc/init.d/ssh ] && /etc/init.d/ssh start

case "$LANG" in
	de*)
		MESSAGE="Passwort für Benutzer '$FLL_LIVE_USER' setzen"
		;;
	es*)
		MESSAGE="Seleccione la clave para el usuario '$FLL_LIVE_USER'"
		;;
	*)
		MESSAGE="Set password for user '$FLL_LIVE_USER'"
		;;
esac

echo ""

while grep -q '^$FLL_LIVE_USER:\*:' /etc/shadow; do
	echo "$MESSAGE"
	passwd "$FLL_LIVE_USER"
done

case "$LANG" in
	de*)
		MESSAGE="Weiter mit der Eingabetaste."
		;;
	es*)
		MESSAGE="Pulse Enter para continuar."
		;;
	*)
		MESSAGE="Hit Return to continue."
		;;
esac

echo ""
echo -n "$MESSAGE"
read a

exit 0

